filemountType: ""
csi:
database:
  exposeToHostPort:
  port: 1433
  image:
    repository: mcr.microsoft.com/
    name: azure-sql-edge
    tag: 1.0.7
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 500M
    limits:
      cpu: "2"
      memory: 2G
  pvc_path: "/var/resc/mssql/data"
  pvc_size: 10Gi
