apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.global.appName }}-db-init
  namespace: {{ .Values.global.namespace }}
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        {{ if .Values.additionalLabels }}
        {{- range $key, $val := .Values.additionalLabels }}    
        {{ $key }}: {{ $val | quote }}    
        {{- end}}
        {{ end }}
        app: {{ .Values.global.appName }}
        tier: database
    spec:
      {{ if .Values.global.serviceAccountName }}
      serviceAccountName: {{ .Values.global.serviceAccountName }}
      {{ end }}
      containers:
        - name: {{ .Values.global.appName }}-db-init
          image: {{ .Values.resc.image.repository | default .Values.global.resc.image.repository }}{{ .Values.resc.image.name | default .Values.global.resc.image.name }}:{{ .Values.resc.image.tag | default .Values.global.resc.image.tag }}
          imagePullPolicy: {{ .Values.resc.image.pullPolicy | default .Values.global.resc.image.pullPolicy }}
          command: ["sh", "-c"]
          args: [ "{{ .Values.preStartUpCommand }} cp /tmp/odbc.ini ~/.odbc.ini; alembic upgrade head "]
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          envFrom:
            - configMapRef:
                name: {{ .Values.global.appName }}-database-init-config
            - secretRef:
                name: {{ .Values.global.appName }}-database-init-secret
          volumeMounts:
            - name: config-volume
              mountPath: /tmp/odbc.ini
              subPath: odbc.ini
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.global.appName }}-database-init-config
      restartPolicy: {{ .Values.restartPolicy }}
      {{ if .Values.global.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecret }}
      {{ end }}
  backoffLimit: {{ .Values.backoffLimit }}
