apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.appName }}-vcs-scraper-repositories
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.global.appName }}
      tier: vcs-scraper-repositories
  replicas: 1
  template:
    metadata:
      labels:
        {{ if .Values.additionalLabels }}
        {{- range $key, $val := .Values.additionalLabels }}
        {{ $key }}: {{ $val | quote }}
        {{- end}}
        {{ end }}
        app: {{ .Values.global.appName }}
        tier: vcs-scraper-repositories
        kubeaudit.io/allow-disabled-apparmor: "apparmor-needs-to-be-installed-on-host"
        kubeaudit.io/allow-read-only-root-filesystem-false: "required-to-write-log-files"
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        {{- with include "resc.vcsScraperRepositoriesAnnotations" .}}
          {{- nindent 8 .}}
        {{- end }}
        container.apparmor.security.beta.kubernetes.io/resc--vcs-scraper-repositories: unconfined
    spec:
      {{ if .Values.global.serviceAccountName }}
      serviceAccountName: {{ .Values.global.serviceAccountName }}
      {{ end }}
      containers:
      - name: {{ .Values.global.appName }}-{{ .Values.vcsTypeShort }}-vcs-scraper-repositories
        image: {{ .Values.VCSScraper.image.repository | default .Values.global.VCSScraper.image.repository }}{{ .Values.VCSScraper.image.name | default .Values.global.VCSScraper.image.name }}:{{ .Values.VCSScraper.image.tag | default .Values.global.VCSScraper.image.tag }}
        imagePullPolicy: {{ .Values.VCSScraper.image.pullPolicy | default .Values.global.VCSScraper.image.pullPolicy }}
        command: ["sh", "-c"]
        args: [ "{{ .Values.preStartUpCommand }} celery -A vcs_scraper.repository_collector.common worker --loglevel={{ .Values.config.loglevel }} -E -Q projects"]
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        envFrom:
          - configMapRef:
              name: {{ .Values.global.appName }}-vcs-scraper-repositories-config
          - configMapRef:
              name: {{ .Values.global.appName }}-rabbitmq-config
          {{ if eq .Values.useKubernetesSecret "true"}}
          - secretRef:
              name: {{ .Values.global.appName }}-vcs-instances-secret
          - secretRef:
              name: {{ .Values.global.appName }}-rabbitmq-user-secret
          {{ end }}
        volumeMounts:
          - name: config-volume
            mountPath: {{ .Values.config.vcs_instance_file_path }}
            subPath: vcs_instances_config.json
          {{- $additionalVolumeMounts := include "resc.vcsScraperRepositoriesAdditionalVolumeMounts" . }}
          {{- if $additionalVolumeMounts }}
          {{- with include "resc.vcsScraperRepositoriesAdditionalVolumeMounts" .}}
            {{- nindent 10 .}}
          {{- end }}
          {{- end }}
        env:
          - name: GET_HOSTS_FROM
            value: dns
        securityContext:
          {{ if eq .Values.useKubernetesSecret "true" }}
          allowPrivilegeEscalation: false
          {{ else }}
          allowPrivilegeEscalation: true
          {{ end }}
          readOnlyRootFilesystem: false
          privileged: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
              type: RuntimeDefault
          runAsNonRoot: true
          runAsUser: 10001
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.global.appName }}-vcs-instances-config
        {{- $additionalVolumes := include "resc.vcsScraperRepositoriesAdditionalVolumes" . }}
        {{- if $additionalVolumes }}
        {{- with include "resc.vcsScraperRepositoriesAdditionalVolumes" .}}
          {{- nindent 8 .}}
        {{- end }}
        {{- end }}
      restartPolicy: {{ .Values.restartPolicy }}
      {{ if .Values.global.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecret }}
      {{ end }}
      {{ if .Values.global.serviceAccountName }}
      automountServiceAccountToken: true
      {{ else }}
      automountServiceAccountToken: false
      {{ end }}