{{ if eq .Values.useKubernetesSecret "true"}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.appName }}-redis-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.appName }}
type: Opaque
data:
  {{ if .Values.redis.config.password }}
  REDIS_PASSWORD: {{  .Values.redis.config.password | b64enc }}
  {{ end }}
{{ end }}