apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.appName }}-redis-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.appName }}
data:
  redis-config: |
    maxmemory 1gb
    maxmemory-policy allkeys-lru 
    protected-mode yes
    save 3600 1
