{{ if eq .Values.useKubernetesSecret "true"}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.appName }}-vcs-instances-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.appName }}
data:
  {{- range $vcsInstance := .Values.vcsInstances }}
  {{ if and ($vcsInstance.username) ($vcsInstance.usernameValue) }}
  {{ $vcsInstance.username }}: "{{ $vcsInstance.usernameValue | b64enc }}"
  {{ end }}
  {{ if and ($vcsInstance.token) ($vcsInstance.tokenValue) }}
  {{ $vcsInstance.token }}: "{{ $vcsInstance.tokenValue | b64enc }}"
  {{ end }}
  {{- end }}
{{- end }}
