{{ if eq .Values.global.enableInClusterDatabase "true"}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.appName }}-database-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.appName }}
data:
  {{ if .Values.database.config }}
  {{ if .Values.database.config.password }}
  SA_PASSWORD: "{{ .Values.database.config.password | b64enc }}"
  {{ end }}
  {{ end }}
{{ end }}