{{ if eq .Values.global.enableInClusterDatabase "true"}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.global.appName }}-database-pv-volume
  namespace: {{ .Values.global.namespace }}
  annotations:
    pv.beta.kubernetes.io/gid: "999"
  {{ if ne .Values.filemountType "csi" }}
  labels:
    type: local
  {{ end }}
spec:
  {{ if and (ne .Values.filemountType "windows") (ne .Values.hostOS "windows") }}
  storageClassName: {{ .Values.global.appName }}-sql-storage
  {{ end }}
  capacity:
    storage: {{ .Values.database.pvc_size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  {{ if eq .Values.filemountType "csi" }}
  csi:
    {{- toYaml .Values.csi | nindent 4 }}
  {{ else if or (eq .Values.filemountType "windows") (eq .Values.hostOS "windows") }}
  local:
    path: {{ .Values.database.pvc_path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop
  {{ else }}
  hostPath:
    path: {{ .Values.database.pvc_path }}
  {{ end }}
{{ end }}