{{ if eq .Values.global.enableInClusterDatabase "true"}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.appName }}-database-pv-volume-claim
  namespace: {{ .Values.global.namespace }}
spec:
  {{ if and (ne .Values.filemountType "windows") (ne .Values.hostOS "windows") }}
  storageClassName: {{ .Values.global.appName }}-sql-storage
  {{ end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.pvc_size }}
{{ end }}