apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.global.appName }}-rules-init
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/resc-rules-init: unconfined
      labels:
        app: {{ .Values.global.appName }}
        tier: database
        kubeaudit.io/allow-disabled-apparmor: "apparmor-needs-to-be-installed-on-host"
        kubeaudit.io/allow-read-only-root-filesystem-false: "required-to-write-log-files"
    spec:
      {{ if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.global.serviceAccountName }}
      {{ end }}
      containers:
        - name: {{ .Values.global.appName }}-rules-init
          image: {{ .Values.resc.image.repository | default .Values.global.resc.image.repository }}{{ .Values.resc.image.name | default .Values.global.resc.image.name }}:{{ .Values.resc.image.tag | default .Values.global.resc.image.tag }}
          imagePullPolicy: {{ .Values.resc.image.pullPolicy | default .Values.global.resc.image.pullPolicy }}
          command: ["sh", "-c"]
          args: [ "cat /tmp/RESC-SECRETS-RULE.toml | base64 -d > /resc_backend/RESC-SECRETS-RULE.toml; curl --retry 5 --retry-delay 1 -F 'rule_file=@/resc_backend/RESC-SECRETS-RULE.toml' http://$RESC_API_NO_AUTH_SERVICE_HOST:$RESC_API_SERVICE_PORT/resc/v1/rule-packs?version=$RULE_PACK_VERSION"]
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          envFrom:
            - configMapRef:
                name: {{ .Values.global.appName }}-rules-config
          volumeMounts:
            - name: config-volume
              mountPath: /tmp/
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            privileged: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
            runAsNonRoot: true
            runAsUser: 10001
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.global.appName }}-rules-config
      restartPolicy: {{ .Values.restartPolicy }}
      {{ if .Values.global.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecret }}
      {{ end }}
      {{ if .Values.global.serviceAccountName }}
      automountServiceAccountToken: true
      {{ else }}
      automountServiceAccountToken: false
      {{ end }}
  backoffLimit: {{ .Values.backoffLimit }}
