redis:
  image:
    repository:
    name: redis
    tag: 7.0.12-alpine
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 400m
      memory: 750M
    limits:
      cpu: 500m
      memory: 1G
  config:
    port: 6379
    password:
  exposeToHostPort:
useKubernetesSecret: "true"
preStartUpCommand: ""
additionalLabels: