redis:
  image:
    repository:
    name: redis
    tag: 7.0.11-alpine
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 256Mi
  config:
    port: 6379
    password:
useKubernetesSecret: "true"
preStartUpCommand: ""
additionalLabels: