{{ if eq .Values.useKubernetesSecret "true"}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.appName }}-rabbitmq-user-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.appName }}
data:
  {{ if .Values.rabbitMQ.config.queues_username }}
  RABBITMQ_QUEUES_USERNAME: "{{ .Values.rabbitMQ.config.queues_username | b64enc }}"
  {{ end }}
  {{ if .Values.rabbitMQ.config.queues_password }}
  RABBITMQ_QUEUES_PASSWORD: "{{ .Values.rabbitMQ.config.queues_password | b64enc }}"
  {{ end }}
  {{ if .Values.rabbitMQ.config.queues_username }}
  RABBITMQ_USERNAME: "{{ .Values.rabbitMQ.config.queues_username | b64enc }}"
  {{ end }}
  {{ if .Values.rabbitMQ.config.queues_password }}
  RABBITMQ_PASSWORD: "{{ .Values.rabbitMQ.config.queues_password | b64enc }}"
  {{ end }}
{{ end }}