apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.appName }}-rabbitmq
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.appName }}
    tier: rabbitmq
spec:
  ports:
    - port: {{ .Values.rabbitMQ.config.port}}
      targetPort: {{ .Values.rabbitMQ.config.port}}
      name: amqp
    - port: {{ .Values.rabbitMQ.config.mgmtPort}}
      targetPort: {{ .Values.rabbitMQ.config.mgmtPort}}
      name: mgmt
  selector:
    app: {{ .Values.global.appName }}
    tier: rabbitmq
