{{ if eq .Values.useKubernetesSecret "true"}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.appName }}-rabbitmq-admin-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.appName }}
data:
  {{ if .Values.rabbitMQ.config.admin_username }}
  RABBITMQ_DEFAULT_USER: "{{ .Values.rabbitMQ.config.admin_username | b64enc  }}"
  {{ end }}
  {{ if .Values.rabbitMQ.config.admin_password }}
  RABBITMQ_DEFAULT_PASS: "{{ .Values.rabbitMQ.config.admin_password | b64enc  }}"
  {{ end }}
{{ end }}