resc:
  image:
    repository:
    name:
    tag:
    pullPolicy:
restartPolicy: "OnFailure"
backoffLimit: 10
resources:
  requests:
    cpu: 100m
    memory: 100M
  limits:
    cpu: 300m
    memory: 500M