name: Backend basic validation

on:
  push:
    branches:
      - '**'
    paths:
      - components/resc-backend/**
      - .github/workflows/backend-**

  pull_request:
    branches:
      - '**'

env:
  RESC_BACKEND_DIR: components/resc-backend

jobs:
  Basic-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install test dependencies
        run: |
          cd ${{ env.RESC_BACKEND_DIR }}
          pip install -r test-requirements.txt
          tox

      - name: Run unittests
        run: |
          cd ${{ env.RESC_BACKEND_DIR }}
          tox -e pytest

      - name: Run linting and sorting checks
        run: |
          cd ${{ env.RESC_BACKEND_DIR }}
          tox -e lint
          tox -e sort
